stages:
  - build
  - test

cache:
  paths:
    - "build"
    - "apt-cache"

before_script:
  # - apt-get update
  # - apt-get -o dir::cache::archives="apt-cache" install -qq -y cmake
  - wget https://cmake.org/files/v3.11/cmake-3.11.0-rc4.tar.gz
  - tar xvzf cmake-3.11.0-rc4.tar.gz
  - cd cmake-3.11.0-rc4
  - ./configure && make && make install
  - cd ..

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release ..
    - cmake --build .

test:
  stage: test
  script:
    - cd build
    - ctest --verbose
